name: Bump patch version

on:
  push:
    branches:
      - Develop
      - Green

permissions:
  contents: write  # 👈 Esto le da permiso al bot para hacer push

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Bump patch version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npm version patch --no-git-tag-version
          git add package.json package-lock.json
          git commit -m "ci: bump patch version [skip ci]"
          git push
