name: Auto Bump Version

on:
  pull_request:
    types: [opened, reopened, closed]

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest

    if: |
      (github.event.action == 'opened' || github.event.action == 'reopened') && github.event.pull_request.base.ref == 'develop'
      || (github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set bump type
        id: bump
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "develop" ]]; then
            echo "type=patch" >> $GITHUB_OUTPUT
          else
            echo "type=major" >> $GITHUB_OUTPUT
          fi

      - name: Bump version ${{ steps.bump.outputs.type }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npm version ${{ steps.bump.outputs.type }} --no-git-tag-version
          git add package.json
          [ -f package-lock.json ] && git add package-lock.json
          git commit -m "ci: bump ${{ steps.bump.outputs.type }} version to $(node -p \"require('./package.json').version\") [skip ci]"
          git push
