name: CI Fail Test

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch: # para correrlo manualmente también

jobs:
  fail_job:
    runs-on: ubuntu-latest
    steps:
      - name: Intentionally fail
        run: exit 1
        
